### ISSUE TITLE
ERROR: Unable to open RTTM file: exp/ES2005a.rttm

### ISSUE THREAD

**Issue by mfawadakbar** [BUTSpeechFIT/VBx#14]
I am facing this error while running run_example script. I have installed all the packages. Please see below the full error,
```
#############################################################################
###
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kal
di-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profi
le)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
#############################################################################
###
Traceback (most recent call last):
  File "/tmp/VBx/VBx/predict.py", line 15, in <module>
    import soundfile as sf
  File "/home/khanreaper/anaconda3/envs/my_env/lib/python3.9/site-packages/so
undfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
#############################################################################
###
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kal
di-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profi
le)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
#############################################################################
###
Traceback (most recent call last):
  File "/tmp/VBx/VBx/vbhmm.py", line 91, in <module>
    segs_dict = read_xvector_timing_dict(args.segments_file)
  File "/tmp/VBx/VBx/diarization_lib.py", line 137, in read_xvector_timing_di
ct
    segs = np.loadtxt(kaldi_segments, dtype=object)
  File "/home/khanreaper/anaconda3/envs/my_env/lib/python3.9/site-packages/nu
mpy/lib/npyio.py", line 1065, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/khanreaper/anaconda3/envs/my_env/lib/python3.9/site-packages/nu
mpy/lib/_datasource.py", line 194, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/khanreaper/anaconda3/envs/my_env/lib/python3.9/site-packages/nu
mpy/lib/_datasource.py", line 531, in open
    raise IOError("%s not found." % path)
OSError: exp/ES2005a.seg not found.
Loading speaker turns from reference RTTMs...
Loading speaker turns from system RTTMs...
ERROR: Unable to open RTTM file: exp/ES2005a.rttm
```

My conda environment is setup as follows,
```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/khanreaper/anaconda3/envs/my_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2021.4.13            h06a4308_1  
certifi                   2020.12.5        py39h06a4308_0  
cffi                      1.14.5                   pypi_0    pypi
h5py                      3.2.1                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
kaldi-io                  0.9.4                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_1  
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.20.2                   pypi_0    pypi
onnxruntime               1.7.0                    pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
pip                       21.0.1           py39h06a4308_0  
protobuf                  3.15.8                   pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
python                    3.9.4                hdb3f193_0  
readline                  8.1                  h27cfd23_0  
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
setuptools                52.0.0           py39h06a4308_0  
six                       1.15.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sortedcontainers          2.3.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.35.4               hdfb4753_0  
tabulate                  0.8.9                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.8.1                    pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
tzdata                    2020f                h52ac0ba_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

Can you please help with this?

**Comment by vinayentc** [comment]
Hi,
As can see from the error-     raise OSError('sndfile library not found'), OSError: sndfile library not found
soundfile library used in predict.py requires libsndfile1. Please install the same. Below command can be used -
apt-get install -y libsndfile1

**Comment by mfawadakbar** [comment]
Thank you for your response. I figured that out. I think you should make some changes in the requirements since **soundfile** is not available anymore

**Comment by fnlandini** [comment]
I am sorry but what do you mean by _not available anymore_? I have just tried following the instructions for installation [here](https://pysoundfile.readthedocs.io/en/latest/) and I did not have any issues.

**Comment by mfawadakbar** [comment]
The requirements.txt uses the package name "soundfile". I am using Linux and I was getting package unmatched error because I couldn't find soundfile. Apparently, the name was actually SoundFile.
You can close this issue BTW.
