### ISSUE TITLE
run_example not giving full output my wav

### ISSUE THREAD

**Issue by mfawadakbar** [BUTSpeechFIT/VBx#15]
Dear Author,
I got the following results for a 55 minutes long wav file with a bit rate of 256kbps. I think it is not giving me the full output. What do I have to change in **run_example.py** to make it compatible with my wav file?

```
SPEAKER ES2005a 1 0.000000 15.000000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 15.000000 2.160000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 17.160000 1.440000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 18.600000 6.550000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 25.520000 8.970000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 35.900000 1.550000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 38.330000 2.070000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 40.420000 18.120000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 58.540000 4.320000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 62.860000 4.080000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 66.940000 0.480000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 67.420000 13.440000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 80.860000 0.720000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 81.580000 6.960000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 88.540000 1.920000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 90.460000 5.280000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 95.740000 0.960000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 96.700000 1.200000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 97.900000 0.240000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 98.140000 1.680000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 99.820000 2.880000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 102.700000 4.000000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 106.710000 26.950000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 133.880000 2.380000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 137.190000 3.000000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 140.190000 2.570000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 143.040000 2.760000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 145.800000 3.600000 <NA> <NA> 2 <NA> <NA>
SPEAKER ES2005a 1 149.400000 22.320000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 171.720000 7.690000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 180.430000 1.800000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 182.230000 0.720000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 182.950000 15.440000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 199.710000 0.330000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 201.710000 8.760000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 210.470000 3.740000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 214.860000 0.300000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 215.210000 8.800000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 225.080000 1.080000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 226.160000 0.840000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 228.960000 6.360000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 235.320000 3.360000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 238.680000 2.300000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 241.370000 0.960000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 243.630000 1.080000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 244.710000 3.810000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 250.200000 1.590000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 253.100000 1.550000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 255.080000 0.980000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 266.840000 2.430000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 276.780000 0.840000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 277.620000 2.160000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 279.780000 0.720000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 280.500000 2.690000 <NA> <NA> 31 <NA> <NA>
SPEAKER ES2005a 1 283.870000 2.520000 <NA> <NA> 31 <NA> <NA>
SPEAKER ES2005a 1 286.390000 0.720000 <NA> <NA> 3 <NA> <NA>
SPEAKER ES2005a 1 287.110000 12.480000 <NA> <NA> 14 <NA> <NA>
SPEAKER ES2005a 1 299.590000 2.210000 <NA> <NA> 19 <NA> <NA>
SPEAKER ES2005a 1 302.140000 4.450000 <NA> <NA> 19 <NA> <NA>
```

**Comment by fnlandini** [comment]
Hello,
Note that the script loads a [.lab file](https://github.com/BUTSpeechFIT/VBx/blob/master/example/vad/ES2005a.lab) which contains the segments with speech. If you want to run the code on your file, you should create such file with the voice activity detection (VAD) marks. This recipe does not run VAD by default.
You could run VAD using this [script](https://github.com/BUTSpeechFIT/VBx/blob/v1.1_VoxConverse2020/VAD/energy_VAD.py) that we shared in a different branch.

**Comment by mfawadakbar** [comment]
Thank you for your response. Could you please specify how to use this file? i am getting the following error
```
:~/VBx/VAD$ python energy_VAD.py AUDIO.wav 
usage: energy_VAD.py [-h] [--in-audio-dir IN_AUDIO_DIR]
                     [--vad-out-dir VAD_OUT_DIR] [--list LIST]
                     [--in-format IN_FORMAT] [--threshold THRESHOLD]
                     [--median-window-length MEDIAN_WINDOW_LENGTH]
energy_VAD.py: error: unrecognized arguments: meeting_mono.wav
```

**Comment by mfawadakbar** [comment]
I tried the following as well
```
python energy_VAD.py --in-audio-dir "/home/USER/VBx/VAD/AUDIO.wav" --vad-out-dir "/home/USER/VBx/VAD"
```

received error below

```
Traceback (most recent call last):
  File "energy_VAD.py", line 115, in <module>
    main()
  File "energy_VAD.py", line 97, in main
    txt_list = [ line.rstrip() for line in open(args.list,'r') ]
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by mfawadakbar** [comment]
Got it! Sorry about that. Here is how to run the file. I got it running

`python energy_VAD.py --in-audio-dir [DIR_TO_AUDIO_FILE] --vad-out-dir [DIR_TO_OUTPUT_VAD] --list [TXT_FILE_WITH_LIST_OF_AUDIO_NAMES] --in-format [EXTENSION_OF_AUDIO]`
